Usy 15 home/search
WildCodeSchool-2024-02/JS-Nantes-RamCSS-P3-BabyPlace pull request #60
Opened 2024-07-11 14:15 UTC by Adeline44

2024-07-11 14:23 UTC, Pas-nou commented on client/src/components/components_parent/FilterBar.jsx
> +          id=""
Un id vide?

2024-07-11 14:23 UTC, Pas-nou commented on client/src/components/components_parent/FilterBar.jsx
> +          id=""
Idem, c'est normal l'id vide?

2024-07-11 14:24 UTC, julien44830 commented on client/src/components/components_parent/FilterBar.jsx
> +          id=""
la aussi : 
```id=""```

2024-07-11 14:24 UTC, Pas-nou commented on client/src/components/components_parent/NurseryCard.jsx
> +        <img src="" alt="" />
Je crois qu'il y a un problème sur ton SRC et ton ALT, ils sont vides :)

2024-07-11 14:26 UTC, julien44830 commented on client/src/pages/page_parents/AccesInvite.jsx
> +import { Button, Input, Checkbox, DatePicker } from "@nextui-org/react";
trop lol : 
```
import { Button } from "@nextui-org/button";
import { Input } from "@nextui-org/input";
import { DatePicker } from "@nextui-org/date-picker";
import { Button, Input, Checkbox, DatePicker } from "@nextui-org/react";
```

2024-07-11 14:27 UTC, Pas-nou commented on client/src/pages/page_parents/AccesInvite.jsx
> +import { Button, Input, Checkbox, DatePicker } from "@nextui-org/react";
Effectivement avec le retrait de la bibliothèque, il faut mettre : 

```
import { Button } from "@nextui-org/button";
import { Input } from "@nextui-org/input";
import { DatePicker } from "@nextui-org/date-picker";
```

2024-07-11 14:28 UTC, Pas-nou commented on client/src/pages/styles_parents/AccesInvite.css
> +  color: var(--ligth-color-text, rgb(255, 255, 255)) !important;
Tu n'utilises pas les variables de couleur ? :)

2024-07-11 14:30 UTC, Pas-nou commented on client/src/pages/styles_parents/HomeSearch.css
> +  background-color: #f1e4ff;
ça pourrait être cool, de la passer en variable, peut-être que cette couleur est utilisée ou sera réutilisée derrière :)

2024-07-11 14:30 UTC, Pas-nou commented on client/src/pages/styles_parents/HomeSearch.css
> +  background-color: #ece7e7;
idem pour la variable de couleur :)

2024-07-11 14:31 UTC, julien44830 commented on client/src/components/styles_components/NurseryCard.css
> +  background-color: white;
Pascal n'a pas parlé de la variable de couleur: 
```
  background-color: white;
```

2024-07-11 14:32 UTC, Pas-nou requested changes
Attention, il y a quelques petites choses à reprendre :)

2024-07-11 14:33 UTC, julien44830 commented on client/src/components/components_parent/NurseryCard.jsx
> +        <img src="" alt="" />
mettre une image en dure temps que le fetch de la BDD n'est pas fait : 
```
 <img src="" alt="" />
```

2024-07-11 14:35 UTC, julien44830 requested changes
2/3 changement correction à faire, pas grand chose

2024-07-16 08:23 UTC, julien44830 approved these changes
bravos

2024-07-16 08:23 UTC, julien44830 commented on client/src/pages/page_parents/AccesInvite.jsx
> +    // Permet de cocher mais pas de décocher
ce commentaire est-il toujours vrai ? : 
`  // Permet de cocher mais pas de décocher`

2024-07-16 08:39 UTC, Pas-nou approved these changes

2024-07-16 08:51 UTC, MrLootman approved these changes

2024-07-16 08:51 UTC, merged