Usy 150 pro signup
WildCodeSchool-2024-02/JS-Nantes-RamCSS-P3-BabyPlace pull request #61
Opened 2024-07-11 15:34 UTC by Pas-nou

Finalisation de l'inscription pour la partir crèche

2024-07-11 15:39 UTC, julien44830 approved these changes
GG

2024-07-11 15:39 UTC, julien44830 commented on client/src/assets/css/global.css
> +  --input-disable-background: rgb(106, 37, 170);
c'est beau : 
```
rgb(106, 37, 170);
```

2024-07-12 07:15 UTC, Pas-nou commented on client/src/assets/css/global.css
> +  --input-disable-background: rgb(106, 37, 170);
Merci je sais :)

2024-07-12 07:52 UTC, AlexisGlln approved these changes
so long but ok for me think to commit more often

2024-07-12 07:57 UTC, MrLootman commented on client/src/components/components_parent/LoginParent.jsx
Vous utilisez des useMemo et des useCallback à tour de bras. Ma question est : Pour quelles raisons valables ?

2024-07-12 07:57 UTC, MrLootman commented
Pull Request invalide en l'état : La mémoïzation est abusivement utilisée pour des raisons obscures.

2024-07-12 08:00 UTC, Pas-nou commented on client/src/components/components_parent/LoginParent.jsx
@julien44830 C'est pas cool, snif

2024-07-12 12:17 UTC, Pas-nou commented
Code optimization, removal of 2 useMemo + 2 useCallback + 1 useEffect per file

2024-07-12 12:22 UTC, julien44830 approved these changes
c'est ok comme la chanson

2024-07-12 12:40 UTC, MrLootman requested changes
Merci de procéder aux changements

2024-07-12 12:40 UTC, MrLootman commented on client/src/components/components_parent/LoginParent.jsx
> +      setEmail(false);
Problème de cohérence de type à régler

2024-07-12 12:40 UTC, MrLootman commented on client/src/components/components_parent/LoginParent.jsx
> +      console.info("Logged", res);
console.info à supprimer

2024-07-12 12:40 UTC, MrLootman commented on client/src/components/components_parent/LoginParent.jsx
> +      if (setEmail && setPassword) {
Vérification de la fonction setEmail et setPassword ?

2024-07-12 12:50 UTC, MrLootman requested changes
vous êtes presques au bout

2024-07-12 12:50 UTC, MrLootman commented on client/src/components/components_pro/SignUpPro.jsx
> +            document.getElementById("confirm-password") &&
tous les doms -> ref

2024-07-12 12:50 UTC, MrLootman commented on client/src/components/components_pro/SignUpPro.jsx
> +        {document.activeElement ===
same

2024-07-12 13:35 UTC, julien44830 commented
ma vision me dit 
````
T OK
 ```

2024-07-13 19:52 UTC, julien44830 commented on client/src/pages/page_parents/ConnexionParent.jsx
> +// import { useEffect } from "react";
très certainement un oublie de suppression de commentaire : `// import { useEffect } from "react";`
en même temps Pascal aime les commentaires

2024-07-13 19:53 UTC, julien44830 commented on client/src/pages/page_pro/ConnexionPro.jsx
> +// import { useEffect } from "react";
même combat : `// import { useEffect } from "react";`

2024-07-15 12:27 UTC, MrLootman approved these changes

2024-07-15 12:28 UTC, merged